apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-0zcc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0069-tenant/tkrw-pr712-0075-0069-app/devfile-sample-0zcc@sha256:31068b1cfc04dc18b7f641b03bdb1c9fff17cbac6198225e97a4b7c1ebf52a72
        name: my-nodejs
        resources: {}
status: {}
